openapi: 3.0.3
info:
  title: Corporation API
  description: Corporation management API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /health:
    get:
      summary: Health check
      description: Check if the API service is healthy and running
      operationId: healthCheck
      tags:
        - health
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                    description: Health status of the service
                required:
                  - status
  /corporations:
    get:
      summary: Get all corporations
      description: Retrieve a list of all corporations with optional filtering and pagination
      tags:
        - Corporations
      parameters:
        - name: limit
          in: query
          description: Maximum number of corporations to return
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 1000
            default: 100
        - name: offset
          in: query
          description: Number of corporations to skip for pagination
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: corporate_number
          in: query
          description: Filter by corporate number
          required: false
          schema:
            type: string
            pattern: ^[0-9]{13}$
        - name: name
          in: query
          description: Filter by corporation name (partial match)
          required: false
          schema:
            type: string
            maxLength: 255
        - name: prefecture
          in: query
          description: Filter by prefecture
          required: false
          schema:
            type: string
            maxLength: 10
        - name: prefecture_code
          in: query
          description: Filter by prefecture code (JIS X 0401 codes 01-47)
          required: false
          schema:
            type: string
            pattern: ^(0[1-9]|[1-4][0-9])$
      responses:
        '200':
          description: List of corporations
          content:
            application/json:
              schema:
                type: object
                properties:
                  corporations:
                    type: array
                    items:
                      $ref: '#/components/schemas/Corporation'
                  total:
                    type: integer
                    description: Total number of corporations
                  limit:
                    type: integer
                    description: Limit used for pagination
                  offset:
                    type: integer
                    description: Offset used for pagination
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /corporations/{corporate_number}:
    get:
      summary: Get corporation by corporate number
      description: Retrieve a specific corporation by its corporate number
      tags:
        - Corporations
      parameters:
        - name: corporate_number
          in: path
          required: true
          description: The corporate number (13 digits)
          schema:
            type: string
            pattern: ^[0-9]{13}$
      responses:
        '200':
          description: Corporation found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Corporation'
        '400':
          description: Invalid corporate number format
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Corporation not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
  schemas:
    Corporation:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Corporation ID
          example: 1
        corporate_number:
          type: string
          description: 13-digit corporate number
          pattern: ^[0-9]{13}$
          example: '1234567890123'
        name:
          type: string
          description: Corporation name
          example: 株式会社サンプル
        kana:
          type: string
          nullable: true
          description: Corporation name in katakana
          example: カブシキガイシャサンプル
        name_en:
          type: string
          nullable: true
          description: Corporation name in English
          example: Sample Corporation
        postal_code:
          type: string
          nullable: true
          description: Postal code
          example: 100-0001
        location:
          type: string
          nullable: true
          description: Head office location
          example: 東京都千代田区千代田1-1
        prefecture_code:
          type: string
          nullable: true
          description: Prefecture code (JIS X 0401)
          pattern: ^[0-9]{2}$
          example: '13'
        status:
          type: string
          description: Corporation status
          example: '01'
        close_date:
          type: string
          format: date
          nullable: true
          description: Registration closure date
          example: '2023-12-01'
        close_cause:
          type: string
          nullable: true
          description: Registration closure reason
          example: 解散
        representative_name:
          type: string
          nullable: true
          description: Representative name
          example: 田中太郎
        representative_position:
          type: string
          nullable: true
          description: Representative position
          example: 代表取締役
        date_of_establishment:
          type: string
          format: date
          nullable: true
          description: Date of establishment
          example: '2020-01-01'
        founding_year:
          type: integer
          nullable: true
          description: Founding year
          example: 2020
        capital_stock:
          type: integer
          format: int64
          nullable: true
          description: Capital stock
          example: 10000000
        employee_number:
          type: integer
          nullable: true
          description: Number of employees
          example: 100
        company_size_male:
          type: integer
          nullable: true
          description: Company size (male employees)
          example: 60
        company_size_female:
          type: integer
          nullable: true
          description: Company size (female employees)
          example: 40
        business_items:
          type: string
          nullable: true
          description: Business items (JSON format)
          example: '["ソフトウェア開発", "システム運用"]'
        business_summary:
          type: string
          nullable: true
          description: Business summary
          example: ITソリューション事業
        company_url:
          type: string
          nullable: true
          description: Company website URL
          example: https://example.com
        qualification_grade:
          type: string
          nullable: true
          description: Qualification grade
          example: A
        number_of_activity:
          type: string
          nullable: true
          description: Number of activity
          example: '1'
        update_date:
          type: string
          format: date
          nullable: true
          description: Last updated date from gBizINFO
          example: '2023-12-01'
        created_at:
          type: string
          format: date-time
          description: Created time
          example: '2023-12-01T09:00:00Z'
        updated_at:
          type: string
          format: date-time
          description: Updated time
          example: '2023-12-01T09:00:00Z'
      required:
        - id
        - corporate_number
        - name
        - status
        - created_at
        - updated_at
